chatbot/urls.py
from django.urls import path

from . import views

app_name = 'chatbot'
urlpatterns = [
    path('<slug:slug>', views.ChatBot.as_view(), name='chatbot'),
    path('api/conversation', views.ChatBotView.as_view(), name='chatbotconversation'),
]

combination_project/urls.py
from django.contrib import admin
from django.urls import include, path
from chatbot import views

app_name = 'combination_project'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('chatbot/', include('chatbot.urls')),
    path('', include('core.urls')),
]

core/urls.py
from django.urls import path

from . import views


app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('api/combinationdata', views.CombinationdataViewSet.as_view(), name='core_combinationdata'),
    path('api/pollsquestion', views.PollsQuestionViewSet.as_view(), name='core_pollsquestion'),
]

chatbot/models.py
from django.db import models

# Create your models here.

chatbot/views.py
import os
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from core.models import PollsQuestion
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
import openai

def ask_open_ai(input_messages):
    if input_messages:
        openai.api_key = os.getenv("OPENAI_API_KEY")
        response = openai.ChatCompletion.create(
            model = "gpt-3.5-turbo",
            messages = input_messages
        )
        return response.choices[0]
    return None


def replace_placeholders(text, replacements):
    for placeholder, value in replacements.items():
        text = text.replace(placeholder, value)
    return text


class ChatBot(View):
    def get(self, request, slug):
        questions = PollsQuestion.objects.filter(objecttype=slug)

        if slug == 'combinationdata':
            replacements = {
                "[CROP_NAME]": request.GET.get('parentcropid', 'Vegetables'),
                "[VARIETIES_NAME]": request.GET.get('mastercropid', 'Carrots'),
                "[HARVESTSTAGE_NAME]": request.GET.get('growingmethodid', 'Full-Size'),
            }

            for question in questions:
                question.questiontext = replace_placeholders(question.questiontext, replacements)

        return render(request, 'chatbot/chatbottemp.html', {"questions": questions})
                      
    def post(self, request, slug):
        message = request.POST['message']
        chatbot_response = ask_open_ai(message)
        return JsonResponse(chatbot_response)
    

class ChatBotView(APIView):
     def post(self, request):
        messages = request.data.get('messages')
        if messages:
            chatbot_response = ask_open_ai(messages)
            if chatbot_response:
                return Response(data=chatbot_response, status=status.HTTP_200_OK)
        return Response(data="No message found", status=status.HTTP_400_BAD_REQUEST)

templates/chatbot/chatbot.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Chat Bot Suggestion{% endblock %}

{% block styles %}
<link href="{% static 'chatbot/css/chatbot.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="chat-container">
    <!-- <div class="col-sm-3">
        <table>
            <tr>
                <th>Parent Crop</th>
                <th>Master Crop</th>
                <th>Growing Method</th>
            </tr>
            {% for item in combi %}
            <tr>
                    <td>{{item.parentcropid}}</td>
                    <td>{{item.mastercropid}}</td>
                    <td>{{item.growingmethodid|default:"Giá trị mặc định"}}</td>
            </tr>
            {% endfor %}
        </table>
    </div> -->
    <div class="card flex-grow-1">
        <div class="card-header bg-primary text-white">Chat</div>
        <div class="card-body messages-box">
            <ul class="list-unstyled messages-list">
                {% for chat in chats %}
                <li class="message sent">
                    <div class="message-text">
                        <div class="message-sender">
                            <b>You</b>
                        </div>
                        <div class="message-content">
                            <p>{{chat.message}}</p>
                        </div>
                    </div>
                </li>

                <li class="message received">
                    <div class="message-text">
                        <div class="message-sender">
                            <b>AI Chatbot</b>
                        </div>
                        <div class="message-content">
                            <p>{{chat.response}}</p>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>

    <form class="message-form">
        {%csrf_token%}
        <div class="input-group">
            <input type="text" class="form-control message-input" placeholder="Type your message..." value="{{questions.first.questiontext}}">
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary btn-send">Send</button>
            </div>
        </div>
    </form>
</div>

{% block scripts %}
<script src=" {% static 'chatbot/js/chatbot.js' %} "></script>
{% endblock %}

{% endblock %}


<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Open AI Chat Bot</title>
</head>
<body>
    <h3>Input anything</h3>

    <form action="" method="post">
        {% csrf_token %}
        <input type="text" class="form-control" name="user-input">
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    {% if chatbot_response %}
    <p>{{ chatbot_response}}</p>
    {% endif %}
</body>
</html> -->

templates/chatbot/chatbottemp.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}TEND - Chat Bot Suggestion{% endblock %}

{% block styles %}
<link href="{% static 'chatbot/css/chatbottemp.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex">
                        <div class="col-6">
                            <h3>TEND - Chat GPT</h3>
                        </div>
                        <div class="col-6 text-right">
                            <a type="button" onclick="window.print()" class="btn  btn-outline-info">Print</a>
                            <a type="button" class="btn btn-outline-danger " onclick="clearContent()">Clear</a>
                            <label class="switch mb-0 pl-5">
                                <input type="checkbox" id="darkModeToggle">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="card-body chat-box rounded p1" id="chatbox">
                    <span id="copy-popup" class="popup">Copied!</span>
                </div>
                <div class="card-footer">
                    <form class="message-form" method="POST" action="{% url 'chatbot:chatbotconversation' %}">
                        {%csrf_token%}
                        <div class="form-group row">
                            <div class="col-md-10">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="inputGroup-sizing-default">More
                                            Suggest</span>
                                        <button type="button"
                                            class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <span class="sr-only">Toggle Dropdown</span>
                                        </button>
                                        <div class="dropdown-menu">
                                            <div class="list-group list-group-flush scrollable-list" id="buttonGroup">
                                                {% for question in questions %}
                                                {% if question %}
                                                <button type="button"
                                                    class="text-left list-group-item {% if forloop.first %}active{% endif %}">{{ question }}</button>
                                                {% endif %}
                                                {% empty %}
                                                <p class="m-0 list-group-item">No more suggestion</p>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                    <textarea id="userInput" rows="1" class="form-control dark-theme auto-expand"
                                        placeholder="Type your message here...">{{ questions.0 }}</textarea>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="input-group-append">
                                    <input id="sendButton" type="button" value="Submit"
                                        class="form-control btn btn-success btn-block"></input>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src=" {% static 'chatbot/js/chatbottemp.js' %} "></script>
{% endblock %}